version: '3.9'
services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:4000
      - VITE_AI_AGENT_URL=http://localhost:8000
    depends_on:
      - backend
      - ai_agent

  backend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../backend:/app
    command: sh -c "npm install && npm run start"
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - AI_AGENT_URL=http://ai_agent:8000
    depends_on:
      - ai_agent

  ai_agent:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ../ai_agent:/app
    command: sh -c "pip install -r requirements.txt && uvicorn src.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"

networks:
  default:
    name: ai_negotiator_net

